export const modGestProp = {
  alquilerTradicional: [
    "Agendamiento de visita",
    "Separación",
    "Agendamiento para notaria (traspaso)",
    "Pago restante del valor de la propiedad",
    "Firma de contrato",
    "Pago de comisión a intermediario inmobiliario",
    "Entrega de llaves y fin de la intermediación",
    "No cierre",
    "Alquilado",
    "Otro",
  ],
  compra: [
    "Agendamiento de visita",
    "Separación",
    "Agendamiento para notaria (traspaso)",
    "Pago restante del valor de la propiedad",
    "Firma de contrato",
    "Pago de comisión a intermediario inmobiliario",
    "Entrega de llaves y fin de la intermediación",
    "No cierre",
    "Alquilado",
    "Otro",
  ],
  alquilerFlex: [
    "En consulta",
    "Reservado",
    "Propiedad en uso",
    "Uso completado",
    "En devolución",
    "Otro",
  ],
};

export const dataPropietarios = [
  {
    id: 1,
    codigo_de_propiedad: 1234567890123,
    estado: "Pendiente de asignar",
    ubicacion: "Malecón de Miraflores, ciudad de Lima, Perú",
    direccion: "Malecón de Miraflores",
    distrito: "Miraflores",
    provincia: "Lima",
    departamento: "Lima",
    codigo_postal: "--",
    referencia: "--",
    modalidad_de_propiedad: "Alquiler tradicional",
    categoria_de_propiedades: "Propiedad residencial",
    tipo_de_propiedad: "Departamento",
    propiedades: "1 propiedad",
    fecha: "Domingo 26 de Noviembre",
    hora_de_inicio_visita: "2:00 pm",
    hora_de_fin_visita: "4:00 pm",
    primer_nombre: "Jesús",
    primer_apellido: "Alzamora",
    telefono: "+51 983 159 445",
    trabaja_con_agente: "No",
    detalle_adicional:
      "Quisiera que el agente me llame cuando esté por llegar a la propiedad.",
      agente: "",
      archivos:[],
  },
  {
    id: 2,
    codigo_de_propiedad: 2345678901234,
    estado: "Pendiente de realizar visita",
    ubicacion: "Avenida Arequipa, ciudad de Lima, Perú",
    direccion: "Avenida Arequipa 123",
    distrito: "Lince",
    provincia: "Lima",
    departamento: "Lima",
    codigo_postal: "15074",
    referencia: "Frente al parque",
    modalidad_de_propiedad: "Alquiler flex",
    categoria_de_propiedades: "Propiedad comercial",
    tipo_de_propiedad: "Oficina",
    propiedades: "2 propiedades",
    fecha: "Martes 15 de Diciembre",
    hora_de_inicio_visita: "10:00 am",
    hora_de_fin_visita: "11:30 am",
    primer_nombre: "Ana",
    primer_apellido: "Gómez",
    telefono: "+51 977 234 567",
    trabaja_con_agente: "Sí",
    detalle_adicional: "Buscando alquilar una propiedad a largo plazo.",
    agente: "Isabel Martínez",
    archivos:[],
  },
  {
    id: 3,
    codigo_de_propiedad: 3456789012345,
    estado: "Pendiente de asignar",
    ubicacion: "Calle San Isidro, ciudad de Lima, Perú",
    direccion: "Calle San Isidro 456",
    distrito: "San Isidro",
    provincia: "Lima",
    departamento: "Lima",
    codigo_postal: "15063",
    referencia: "Cerca a la plaza principal",
    modalidad_de_propiedad: "Venta",
    categoria_de_propiedades: "Propiedad residencial",
    tipo_de_propiedad: "Casa",
    propiedades: "3 propiedades",
    fecha: "Martes 15 de Diciembre",
    hora_de_inicio_visita: "10:00 am",
    hora_de_fin_visita: "11:30 am",
    primer_nombre: "Carlos",
    primer_apellido: "Fernández",
    telefono: "+51 944 123 456",
    trabaja_con_agente: "Sí",
    detalle_adicional:
      "Quiero vender esta propiedad, ideal para construcción residencial. ¡Excelente oportunidad!",
      agente: "",
      archivos:[],
  },
  {
    id: 4,
    codigo_de_propiedad: 4567890123456,
    estado: "Pendiente de realizar visita",
    ubicacion: "Jirón de la Unión, ciudad de Lima, Perú",
    direccion: "Jirón de la Unión 789",
    distrito: "Cercado de Lima",
    provincia: "Lima",
    departamento: "Lima",
    codigo_postal: "15001",
    referencia: "Frente a la Plaza Mayor",
    modalidad_de_propiedad: "Alquiler flex",
    categoria_de_propiedades: "Propiedad comercial",
    tipo_de_propiedad: "Almacén",
    propiedades: "1 propiedad",
    fecha: "Jueves 5 de Enero",
    hora_de_inicio_visita: "3:30 pm",
    hora_de_fin_visita: "4:15 pm",
    primer_nombre: "Luisa",
    primer_apellido: "Martínez",
    telefono: "+51 956 789 012",
    trabaja_con_agente: "No",
    detalle_adicional:
      "Necesito un lugar para alquilar durante un mes debido a una mudanza temporal.",
    agente: "Juan López",
    archivos:[],
  },
  {
    id: 5,
    codigo_de_propiedad: 5678901234567,
    estado: "Pendiente de realizar visita",
    ubicacion: "Calle Las Begonias, ciudad de Lima, Perú",
    direccion: "Calle Las Begonias 234",
    distrito: "San Borja",
    provincia: "Lima",
    departamento: "Lima",
    codigo_postal: "15036",
    referencia: "Cerca al parque zonal",
    modalidad_de_propiedad: "Venta",
    categoria_de_propiedades: "Propiedad residencial",
    tipo_de_propiedad: "Departamento",
    propiedades: "2 propiedades",
    fecha: "Miércoles 20 de Marzo",
    hora_de_inicio_visita: "9:00 am",
    hora_de_fin_visita: "10:30 am",
    primer_nombre: "Maria",
    primer_apellido: "López",
    telefono: "+51 977 876 543",
    trabaja_con_agente: "Sí",
    detalle_adicional: "Interesada en comprar un departamento para la familia.",
    agente: "Laura Rodríguez",
    archivos:[],
  },
  {
    id: 6,
    codigo_de_propiedad: 6789012345678,
    estado: "Pendiente de asignar",
    ubicacion: "Avenida Los Conquistadores, ciudad de Arequipa, Perú",
    direccion: "Avenida Los Conquistadores 567",
    distrito: "Cayma",
    provincia: "Arequipa",
    departamento: "Arequipa",
    codigo_postal: "04011",
    referencia: "Cerca al centro comercial",
    modalidad_de_propiedad: "Alquiler tradicional",
    categoria_de_propiedades: "Propiedad comercial",
    tipo_de_propiedad: "Tiendas",
    propiedades: "1 propiedad",
    fecha: "Viernes 8 de Mayo",
    hora_de_inicio_visita: "4:00 pm",
    hora_de_fin_visita: "5:30 pm",
    primer_nombre: "Pedro",
    primer_apellido: "Castillo",
    telefono: "+51 958 321 789",
    trabaja_con_agente: "No",
    detalle_adicional: "Busco un local para iniciar mi propio negocio.",
    agente: "",
    archivos:[],
  },
  {
    id: 7,
    codigo_de_propiedad: 7890123456789,
    estado: "Pendiente de asignar",
    ubicacion: "Jirón Lima, ciudad de Trujillo, Perú",
    direccion: "Jirón Lima 789",
    distrito: "Trujillo",
    provincia: "La Libertad",
    departamento: "La Libertad",
    codigo_postal: "13001",
    referencia: "Cerca al centro histórico",
    modalidad_de_propiedad: "Venta",
    categoria_de_propiedades: "Propiedad residencial",
    tipo_de_propiedad: "Habitaciones",
    propiedades: "2 propiedades",
    fecha: "Sábado 17 de Julio",
    hora_de_inicio_visita: "11:00 am",
    hora_de_fin_visita: "12:30 pm",
    primer_nombre: "Alejandro",
    primer_apellido: "Ramírez",
    telefono: "+51 976 543 210",
    trabaja_con_agente: "Sí",
    detalle_adicional: "Planeo mudarme a Trujillo y comprar una casa.",
    agente: "",
    archivos:[],
  },
  {
    id: 8,
    codigo_de_propiedad: 8901234567890,
    estado: "Pendiente de cerrar contrato",
    ubicacion: "Avenida Grau, ciudad de Chiclayo, Perú",
    direccion: "Avenida Grau 456",
    distrito: "Chiclayo",
    provincia: "Lambayeque",
    departamento: "Lambayeque",
    codigo_postal: "14001",
    referencia: "Frente a la plaza de armas",
    modalidad_de_propiedad: "Alquiler flex",
    categoria_de_propiedades: "Propiedad comercial",
    tipo_de_propiedad: "Industrial",
    propiedades: "1 propiedad",
    fecha: "Lunes 5 de Septiembre",
    hora_de_inicio_visita: "2:30 pm",
    hora_de_fin_visita: "4:00 pm",
    primer_nombre: "Isabel",
    primer_apellido: "García",
    telefono: "+51 994 567 890",
    trabaja_con_agente: "No",
    detalle_adicional: "Necesito una oficina para mi nuevo emprendimiento.",
    agente: "Diego Herrera",
    archivos:[],
  },
  {
    id: 9,
    codigo_de_propiedad: 9012345678901,
    estado: "Pendiente de asignar",
    ubicacion: "Calle Huancavelica, ciudad de Huancayo, Perú",
    direccion: "Calle Huancavelica 321",
    distrito: "Huancayo",
    provincia: "Junín",
    departamento: "Junín",
    codigo_postal: "12001",
    referencia: "Cerca al mercado central",
    modalidad_de_propiedad: "Venta",
    categoria_de_propiedades: "Propiedad residencial",
    tipo_de_propiedad: "Terrenos",
    propiedades: "3 propiedades",
    fecha: "Domingo 12 de Noviembre",
    hora_de_inicio_visita: "3:00 pm",
    hora_de_fin_visita: "4:30 pm",
    primer_nombre: "Rosa",
    primer_apellido: "Hernández",
    telefono: "+51 987 654 321",
    trabaja_con_agente: "Sí",
    detalle_adicional: "Quiero mudarme a Huancayo y comprar un departamento.",
    agente: "",
    archivos:[],
  },
  {
    id: 10,
    codigo_de_propiedad: 1234567890123,
    estado: "Pendiente de realizar visita",
    ubicacion: "Avenida Bolognesi, ciudad de Tacna, Perú",
    direccion: "Avenida Bolognesi 987",
    distrito: "Tacna",
    provincia: "Tacna",
    departamento: "Tacna",
    codigo_postal: "23001",
    referencia: "Cerca a la frontera con Chile",
    modalidad_de_propiedad: "Alquiler tradicional",
    categoria_de_propiedades: "Propiedad comercial",
    tipo_de_propiedad: "Oficina",
    propiedades: "1 propiedad",
    fecha: "Jueves 8 de Diciembre",
    hora_de_inicio_visita: "1:00 pm",
    hora_de_fin_visita: "2:30 pm",
    primer_nombre: "Martín",
    primer_apellido: "Sánchez",
    telefono: "+51 965 432 109",
    trabaja_con_agente: "Sí",
    detalle_adicional: "Buscando un local para abrir un negocio en Tacna.",
    agente: "Paola Sánchez",
    archivos:[],
  },
  {
    id: 11,
    codigo_de_propiedad: 2345678901234,
    estado: "Pendiente de reprogramar visita",
    ubicacion: "Calle Los Pinos, ciudad de Cusco, Perú",
    direccion: "Calle Los Pinos 567",
    distrito: "Cusco",
    provincia: "Cusco",
    departamento: "Cusco",
    codigo_postal: "08001",
    referencia: "Cerca a la Plaza de Armas",
    modalidad_de_propiedad: "Venta",
    categoria_de_propiedades: "Propiedad residencial",
    tipo_de_propiedad: "Departamento",
    propiedades: "1 propiedad",
    fecha: "Sábado 5 de Abril",
    hora_de_inicio_visita: "11:30 am",
    hora_de_fin_visita: "1:00 pm",
    primer_nombre: "Diego",
    primer_apellido: "Vargas",
    telefono: "+51 922 345 678",
    trabaja_con_agente: "Sí",
    detalle_adicional: "En busca de un apartamento con vistas panorámicas.",
    agente: "",
    archivos:[],
  },
  {
    id: 12,
    codigo_de_propiedad: 3456789012345,
    estado: "Pendiente de reprogramar visita",
    ubicacion: "Avenida del Sol, ciudad de Cusco, Perú",
    direccion: "Avenida del Sol 789",
    distrito: "Cusco",
    provincia: "Cusco",
    departamento: "Cusco",
    codigo_postal: "08002",
    referencia: "Próximo a la estación de tren",
    modalidad_de_propiedad: "Alquiler tradicional",
    categoria_de_propiedades: "Propiedad residencial",
    tipo_de_propiedad: "Casa",
    propiedades: "2 propiedades",
    fecha: "Martes 10 de Mayo",
    hora_de_inicio_visita: "3:00 pm",
    hora_de_fin_visita: "4:30 pm",
    primer_nombre: "Laura",
    primer_apellido: "Torres",
    telefono: "+51 933 987 654",
    trabaja_con_agente: "No",
    detalle_adicional: "Familia en busca de una casa acogedora para alquilar.",
    agente: "",
    archivos:[],
  },
  {
    id: 13,
    codigo_de_propiedad: 4567890123456,
    estado: "Pendiente de reprogramar visita",
    ubicacion: "Calle Lima, ciudad de Piura, Perú",
    direccion: "Calle Lima 123",
    distrito: "Piura",
    provincia: "Piura",
    departamento: "Piura",
    codigo_postal: "20001",
    referencia: "Cerca al centro comercial",
    modalidad_de_propiedad: "Venta",
    categoria_de_propiedades: "Propiedad comercial",
    tipo_de_propiedad: "Local",
    propiedades: "1 propiedad",
    fecha: "Viernes 15 de Junio",
    hora_de_inicio_visita: "10:00 am",
    hora_de_fin_visita: "11:30 am",
    primer_nombre: "Julio",
    primer_apellido: "González",
    telefono: "+51 955 123 789",
    trabaja_con_agente: "Sí",
    detalle_adicional:
      "Empresario en busca de un local para expandir su negocio.",
      agente: "",
      archivos:[],
  },
  {
    id: 14,
    codigo_de_propiedad: 5678901234567,
    estado: "Pendiente de reprogramar visita",
    ubicacion: "Avenida Brasil, ciudad de Chiclayo, Perú",
    direccion: "Avenida Brasil 456",
    distrito: "Chiclayo",
    provincia: "Lambayeque",
    departamento: "Lambayeque",
    codigo_postal: "14002",
    referencia: "Cerca al aeropuerto",
    modalidad_de_propiedad: "Alquiler flex",
    categoria_de_propiedades: "Propiedad comercial",
    tipo_de_propiedad: "Industrial",
    propiedades: "1 propiedad",
    fecha: "Miércoles 20 de Julio",
    hora_de_inicio_visita: "2:30 pm",
    hora_de_fin_visita: "4:00 pm",
    primer_nombre: "Gabriela",
    primer_apellido: "Mendoza",
    telefono: "+51 977 567 890",
    trabaja_con_agente: "No",
    detalle_adicional: "Necesito un espacio para almacenamiento a largo plazo.",
    agente: "",
    archivos:[],
  },
  {
    id: 15,
    codigo_de_propiedad: 6789012345678,
    estado: "Pendiente de reprogramar visita",
    ubicacion: "Calle San Martín, ciudad de Trujillo, Perú",
    direccion: "Calle San Martín 789",
    distrito: "Trujillo",
    provincia: "La Libertad",
    departamento: "La Libertad",
    codigo_postal: "13002",
    referencia: "Frente al parque",
    modalidad_de_propiedad: "Venta",
    categoria_de_propiedades: "Propiedad residencial",
    tipo_de_propiedad: "Terreno",
    propiedades: "3 propiedades",
    fecha: "Domingo 25 de Agosto",
    hora_de_inicio_visita: "9:00 am",
    hora_de_fin_visita: "10:30 am",
    primer_nombre: "Fernanda",
    primer_apellido: "Pérez",
    telefono: "+51 966 543 210",
    trabaja_con_agente: "Sí",
    detalle_adicional: "Quiero construir mi propia casa en este terreno.",
    agente: "",
    archivos:[],
  },
  {
    id: 16,
    codigo_de_propiedad: 7890123456789,
    estado: "Pendiente de cerrar contrato",
    ubicacion: "Avenida La Marina, ciudad de Iquitos, Perú",
    direccion: "Avenida La Marina 321",
    distrito: "Iquitos",
    provincia: "Loreto",
    departamento: "Loreto",
    codigo_postal: "16001",
    referencia: "Cerca al río Amazonas",
    modalidad_de_propiedad: "Alquiler tradicional",
    categoria_de_propiedades: "Propiedad residencial",
    tipo_de_propiedad: "Casa",
    propiedades: "1 propiedad",
    fecha: "Lunes 5 de Octubre",
    hora_de_inicio_visita: "1:30 pm",
    hora_de_fin_visita: "3:00 pm",
    primer_nombre: "Hugo",
    primer_apellido: "Ramón",
    telefono: "+51 933 654 321",
    trabaja_con_agente: "Sí",
    detalle_adicional:
      "Buscando una casa de campo para escapadas de fin de semana.",
      agente: "",
      archivos:[],
  },
  {
    id: 17,
    codigo_de_propiedad: 8901234567890,
    estado: "Pendiente de cerrar contrato",
    ubicacion: "Calle Sucre, ciudad de Ayacucho, Perú",
    direccion: "Calle Sucre 567",
    distrito: "Ayacucho",
    provincia: "Ayacucho",
    departamento: "Ayacucho",
    codigo_postal: "05001",
    referencia: "Cerca a la plaza de armas",
    modalidad_de_propiedad: "Venta",
    categoria_de_propiedades: "Propiedad residencial",
    tipo_de_propiedad: "Departamento",
    propiedades: "2 propiedades",
    fecha: "Sábado 15 de Noviembre",
    hora_de_inicio_visita: "10:00 am",
    hora_de_fin_visita: "11:30 am",
    primer_nombre: "Verónica",
    primer_apellido: "Mendoza",
    telefono: "+51 977 876 543",
    trabaja_con_agente: "No",
    detalle_adicional:
      "Interesada en invertir en departamentos para alquiler a largo plazo.",
      agente: "",
      archivos:[],
  },
  {
    id: 18,
    codigo_de_propiedad: 9012345678901,
    estado: "Pendiente de realizar visita",
    ubicacion: "Jirón Grau, ciudad de Huancavelica, Perú",
    direccion: "Jirón Grau 123",
    distrito: "Huancavelica",
    provincia: "Huancavelica",
    departamento: "Huancavelica",
    codigo_postal: "09001",
    referencia: "Frente al mercado central",
    modalidad_de_propiedad: "Alquiler flex",
    categoria_de_propiedades: "Propiedad comercial",
    tipo_de_propiedad: "Local",
    propiedades: "1 propiedad",
    fecha: "Miércoles 20 de Diciembre",
    hora_de_inicio_visita: "2:00 pm",
    hora_de_fin_visita: "3:30 pm",
    primer_nombre: "Manuel",
    primer_apellido: "Cordova",
    telefono: "+51 955 432 109",
    trabaja_con_agente: "Sí",
    detalle_adicional:
      "Planea abrir un negocio en Huancavelica y busca un local adecuado.",
    agente: "Roberto González",
    archivos:[],
  },
  {
    id: 19,
    codigo_de_propiedad: 1234567890123,
    estado: "Pendiente de cerrar contrato",
    ubicacion: "Avenida Salaverry, ciudad de Arequipa, Perú",
    direccion: "Avenida Salaverry 456",
    distrito: "Arequipa",
    provincia: "Arequipa",
    departamento: "Arequipa",
    codigo_postal: "04001",
    referencia: "Cerca a la zona financiera",
    modalidad_de_propiedad: "Venta",
    categoria_de_propiedades: "Propiedad comercial",
    tipo_de_propiedad: "Oficina",
    propiedades: "1 propiedad",
    fecha: "Jueves 5 de Febrero",
    hora_de_inicio_visita: "11:00 am",
    hora_de_fin_visita: "12:30 pm",
    primer_nombre: "Elena",
    primer_apellido: "Santos",
    telefono: "+51 944 789 012",
    trabaja_con_agente: "No",
    detalle_adicional:
      "Busca una oficina para establecer su consultorio legal.",
      agente: "",
      archivos:[],
  },
  {
    id: 20,
    codigo_de_propiedad: 1234567890124,
    estado: "Pendiente de cerrar contrato",
    ubicacion: "Calle Bolívar, ciudad de Lima, Perú",
    direccion: "Calle Bolívar 789",
    distrito: "Barranco",
    provincia: "Lima",
    departamento: "Lima",
    codigo_postal: "15049",
    referencia: "Cerca al malecón",
    modalidad_de_propiedad: "Alquiler tradicional",
    categoria_de_propiedades: "Propiedad residencial",
    tipo_de_propiedad: "Departamento",
    propiedades: "2 propiedades",
    fecha: "Viernes 10 de Marzo",
    hora_de_inicio_visita: "9:30 am",
    hora_de_fin_visita: "11:00 am",
    primer_nombre: "Rodrigo",
    primer_apellido: "Mendoza",
    telefono: "+51 977 654 321",
    trabaja_con_agente: "Sí",
    detalle_adicional:
      "En busca de un apartamento moderno para mudarse con su familia.",
    agente: "Cecilia Fuentes",
    archivos:[],
  },
  {
    id: 21,
    codigo_de_propiedad: 1234567890125,
    estado: "Pendiente de acuerdo con el propietario",
    ubicacion: "Avenida Huaylas, ciudad de Huaraz, Perú",
    direccion: "Avenida Huaylas 456",
    distrito: "Huaraz",
    provincia: "Ancash",
    departamento: "Ancash",
    codigo_postal: "02001",
    referencia: "Cerca a la plaza de armas",
    modalidad_de_propiedad: "Venta",
    categoria_de_propiedades: "Propiedad residencial",
    tipo_de_propiedad: "Terreno",
    propiedades: "2 propiedades",
    fecha: "Sábado 12 de Junio",
    hora_de_inicio_visita: "10:00 am",
    hora_de_fin_visita: "11:30 am",
    primer_nombre: "Gabriel",
    primer_apellido: "Pérez",
    telefono: "+51 911 234 567",
    trabaja_con_agente: "No",
    detalle_adicional: "Interesado en invertir en terrenos para desarrollo urbano.",
    agente: "",
    archivos: [],
  },
  {
    id: 22,
    codigo_de_propiedad: 1234567890126,
    estado: "Pendiente de acuerdo con el propietario",
    ubicacion: "Calle Arequipa, ciudad de Ica, Perú",
    direccion: "Calle Arequipa 789",
    distrito: "Ica",
    provincia: "Ica",
    departamento: "Ica",
    codigo_postal: "11001",
    referencia: "Cerca al centro comercial",
    modalidad_de_propiedad: "Alquiler flex",
    categoria_de_propiedades: "Propiedad comercial",
    tipo_de_propiedad: "Local",
    propiedades: "1 propiedad",
    fecha: "Domingo 20 de Agosto",
    hora_de_inicio_visita: "3:00 pm",
    hora_de_fin_visita: "4:30 pm",
    primer_nombre: "Silvia",
    primer_apellido: "Gutiérrez",
    telefono: "+51 922 345 678",
    trabaja_con_agente: "Sí",
    detalle_adicional: "Busca un local para abrir su propio negocio de moda.",
    agente: "Jorge Rodríguez",
    archivos: [],
  },
  {
    id: 23,
    codigo_de_propiedad: 1234567890127,
    estado: "Pendiente de acuerdo con el propietario",
    ubicacion: "Jirón Bolívar, ciudad de Cajamarca, Perú",
    direccion: "Jirón Bolívar 123",
    distrito: "Cajamarca",
    provincia: "Cajamarca",
    departamento: "Cajamarca",
    codigo_postal: "06001",
    referencia: "Cerca al parque",
    modalidad_de_propiedad: "Venta",
    categoria_de_propiedades: "Propiedad residencial",
    tipo_de_propiedad: "Casa",
    propiedades: "1 propiedad",
    fecha: "Martes 15 de Septiembre",
    hora_de_inicio_visita: "11:00 am",
    hora_de_fin_visita: "12:30 pm",
    primer_nombre: "Miguel",
    primer_apellido: "Rodríguez",
    telefono: "+51 944 567 890",
    trabaja_con_agente: "Sí",
    detalle_adicional: "En busca de una casa con jardín para la familia.",
    agente: "Ana Torres",
    archivos: [],
  },
  {
    id: 24,
    codigo_de_propiedad: 1234567890128,
    estado: "Pendiente de acuerdo con el propietario",
    ubicacion: "Calle Tacna, ciudad de Puno, Perú",
    direccion: "Calle Tacna 456",
    distrito: "Puno",
    provincia: "Puno",
    departamento: "Puno",
    codigo_postal: "21001",
    referencia: "Cerca al lago Titicaca",
    modalidad_de_propiedad: "Alquiler tradicional",
    categoria_de_propiedades: "Propiedad residencial",
    tipo_de_propiedad: "Departamento",
    propiedades: "2 propiedades",
    fecha: "Jueves 10 de Noviembre",
    hora_de_inicio_visita: "2:30 pm",
    hora_de_fin_visita: "4:00 pm",
    primer_nombre: "Patricia",
    primer_apellido: "Fuentes",
    telefono: "+51 911 876 543",
    trabaja_con_agente: "No",
    detalle_adicional: "Estudiante en busca de un departamento para alquilar durante la carrera.",
    agente: "",
    archivos: [],
  },
  {
    id: 25,
    codigo_de_propiedad: 1234567890129,
    estado: "Pendiente de realizar visita",
    ubicacion: "Avenida La Paz, ciudad de Juliaca, Perú",
    direccion: "Avenida La Paz 789",
    distrito: "Juliaca",
    provincia: "Puno",
    departamento: "Puno",
    codigo_postal: "21071",
    referencia: "Cerca al centro comercial",
    modalidad_de_propiedad: "Venta",
    categoria_de_propiedades: "Propiedad comercial",
    tipo_de_propiedad: "Local",
    propiedades: "1 propiedad",
    fecha: "Sábado 5 de Diciembre",
    hora_de_inicio_visita: "10:00 am",
    hora_de_fin_visita: "11:30 am",
    primer_nombre: "Roberto",
    primer_apellido: "Gómez",
    telefono: "+51 933 234 567",
    trabaja_con_agente: "Sí",
    detalle_adicional: "Empresario en busca de un local para abrir una tienda de electrónicos.",
    agente: "María Silva",
    archivos: [],
  },
  {
    id: 26,
    codigo_de_propiedad: 1234567890130,
    estado: "Pendiente precio de propiedad",
    ubicacion: "Calle Lima, ciudad de Ilo, Perú",
    direccion: "Calle Lima 789",
    distrito: "Ilo",
    provincia: "Moquegua",
    departamento: "Moquegua",
    codigo_postal: "11011",
    referencia: "Cerca al puerto",
    modalidad_de_propiedad: "Venta",
    categoria_de_propiedades: "Propiedad comercial",
    tipo_de_propiedad: "Oficina",
    propiedades: "1 propiedad",
    fecha: "Lunes 20 de Febrero",
    hora_de_inicio_visita: "11:30 am",
    hora_de_fin_visita: "1:00 pm",
    primer_nombre: "Johana",
    primer_apellido: "Ortega",
    telefono: "+51 966 789 012",
    trabaja_con_agente: "No",
    detalle_adicional: "Buscando una oficina para establecer su agencia de envíos.",
    agente: "",
    archivos: [],
    verificador: "",
    precios_de_propiedad: null,
    verificador: "",
    precios_de_propiedad: {},
  },
  {
    id: 27,
    codigo_de_propiedad: 1234567890131,
    estado: "Pendiente precio de propiedad",
    ubicacion: "Avenida Bolognesi, ciudad de Chincha, Perú",
    direccion: "Avenida Bolognesi 456",
    distrito: "Chincha",
    provincia: "Ica",
    departamento: "Ica",
    codigo_postal: "11061",
    referencia: "Frente a la plaza principal",
    modalidad_de_propiedad: "Alquiler flex",
    categoria_de_propiedades: "Propiedad residencial",
    tipo_de_propiedad: "Casa",
    propiedades: "2 propiedades",
    fecha: "Miércoles 15 de Marzo",
    hora_de_inicio_visita: "3:00 pm",
    hora_de_fin_visita: "4:30 pm",
    primer_nombre: "Héctor",
    primer_apellido: "Cabrera",
    telefono: "+51 922 567 890",
    trabaja_con_agente: "Sí",
    detalle_adicional: "Familia en busca de una casa con jardín en Chincha.",
    agente: "Carlos Torres",
    archivos: [],
    verificador: "",
    precios_de_propiedad: null,
    verificador: "",
    precios_de_propiedad: {},
  },
  {
    id: 28,
    codigo_de_propiedad: 1234567890132,
    estado: "Pendiente precio de propiedad",
    ubicacion: "Calle Amazonas, ciudad de Tarapoto, Perú",
    direccion: "Calle Amazonas 789",
    distrito: "Tarapoto",
    provincia: "San Martín",
    departamento: "San Martín",
    codigo_postal: "22001",
    referencia: "Cerca al centro de la ciudad",
    modalidad_de_propiedad: "Venta",
    categoria_de_propiedades: "Propiedad residencial",
    tipo_de_propiedad: "Terreno",
    propiedades: "3 propiedades",
    fecha: "Domingo 10 de Abril",
    hora_de_inicio_visita: "10:00 am",
    hora_de_fin_visita: "11:30 am",
    primer_nombre: "Lucía",
    primer_apellido: "Díaz",
    telefono: "+51 944 234 567",
    trabaja_con_agente: "No",
    detalle_adicional: "Interesada en terrenos para proyecto de construcción.",
    agente: "",
    archivos: [],
    verificador: "",
    precios_de_propiedad: null,
    verificador: "",
    precios_de_propiedad: {},
  },
  {
    id: 29,
    codigo_de_propiedad: 1234567890133,
    estado: "Pendiente precio de propiedad",
    ubicacion: "Jirón Grau, ciudad de Tumbes, Perú",
    direccion: "Jirón Grau 123",
    distrito: "Tumbes",
    provincia: "Tumbes",
    departamento: "Tumbes",
    codigo_postal: "24001",
    referencia: "Frente al malecón",
    modalidad_de_propiedad: "Alquiler tradicional",
    categoria_de_propiedades: "Propiedad comercial",
    tipo_de_propiedad: "Local",
    propiedades: "1 propiedad",
    fecha: "Sábado 5 de Mayo",
    hora_de_inicio_visita: "2:30 pm",
    hora_de_fin_visita: "4:00 pm",
    primer_nombre: "Diego",
    primer_apellido: "Vargas",
    telefono: "+51 933 876 543",
    trabaja_con_agente: "Sí",
    detalle_adicional: "Emprendedor en busca de un local para abrir una cafetería.",
    agente: "Laura García",
    archivos: [],
    verificador: "",
    precios_de_propiedad: null,
    verificador: "",
    precios_de_propiedad: {},
  },
  {
    id: 30,
    codigo_de_propiedad: 1234567890134,
    estado: "Pendiente precio de propiedad",
    ubicacion: "Avenida Grau, ciudad de Iquitos, Perú",
    direccion: "Avenida Grau 789",
    distrito: "Iquitos",
    provincia: "Loreto",
    departamento: "Loreto",
    codigo_postal: "16001",
    referencia: "Cerca al mercado",
    modalidad_de_propiedad: "Venta",
    categoria_de_propiedades: "Propiedad comercial",
    tipo_de_propiedad: "Oficina",
    propiedades: "1 propiedad",
    fecha: "Jueves 20 de Junio",
    hora_de_inicio_visita: "11:30 am",
    hora_de_fin_visita: "1:00 pm",
    primer_nombre: "Isabel",
    primer_apellido: "Ramírez",
    telefono: "+51 966 567 890",
    trabaja_con_agente: "No",
    detalle_adicional: "Profesional en busca de una oficina para consultoría.",
    agente: "",
    archivos: [],
    verificador: "",
    precios_de_propiedad: {},
  }
];

export const dataAgentes = [
  {
    id: 1,
    resumen: "resumen1",
    estado: "Pendiente",
    agente_califica: "",
    nombre: "Raúl",
    apellido: "Fernández",
    correo_electronico: "raulfernandez@gmail.com",
    telefono: "+51 983 159 445",
    como_conociste_web: "Publicidad online",
    experiencia_inmobiliaria: "Avanzada",
    agente_externo: "No",
    departamento: "Lima",
    provincia: "Lima",
    distrito: "San Isidro",
    propiedades_asigandos: [],
    cuentanos:
      "Cuento con 5 años de experiencia en el sector inmobiliario. He trabajado en la venta y alquiler de propiedades en la ciudad de Lima, específicamente en el distrito de San Isidro. Mi enfoque se ha centrado en brindar un servicio personalizado y eficiente a mis clientes, comprendiendo sus necesidades y guiándolos a través del proceso de compra o alquiler de manera exitosa. Estoy interesado en explorar nuevas oportunidades y en continuar expandiendo mi experiencia en el mercado inmobiliario.",
  },
  {
    id: 2,
    resumen: "resumen2",
    estado: "Pendiente",
    agente_califica: "",
    nombre: "María",
    apellido: "García",
    correo_electronico: "mariagarcia@gmail.com",
    telefono: "+51 976 234 567",
    como_conociste_web: "Recomendación de amigo",
    experiencia_inmobiliaria: "Intermedia",
    agente_externo: "Sí",
    departamento: "Arequipa",
    provincia: "Arequipa",
    distrito: "Cayma",
    propiedades_asigandos: [],
    cuentanos:
      "Trabajo como agente inmobiliario en Arequipa, con una experiencia intermedia en el campo. Estoy en proceso de atender las necesidades de mis clientes en la búsqueda y adquisición de propiedades. Mi enfoque se centra en proporcionar un servicio de calidad, aprovechando la recomendación de amigos como una fuente valiosa de conexión con nuevos clientes. Siempre estoy dispuesta a explorar nuevas oportunidades y desafíos en el mercado inmobiliario.",
  },
  {
    id: 3,
    resumen: "resumen3",
    estado: "Pendiente",
    agente_califica: "Excelente",
    nombre: "Carlos",
    apellido: "Díaz",
    correo_electronico: "carlosdiaz@gmail.com",
    telefono: "+51 945 876 321",
    como_conociste_web: "Redes Sociales",
    experiencia_inmobiliaria: "Principiante",
    agente_externo: "No",
    departamento: "Cusco",
    provincia: "Cusco",
    distrito: "Cusco",
    propiedades_asigandos: [],
    cuentanos:
      "Estoy buscando mi primera casa en Cusco. A pesar de ser principiante en el ámbito inmobiliario, estoy entusiasmado por encontrar la propiedad perfecta que se adapte a mis necesidades y preferencias. He completado con éxito el proceso de compra y estoy satisfecho con la excelente asesoría recibida. Ahora estoy listo para explorar nuevas posibilidades en el mercado inmobiliario.",
  },
  {
    id: 4,
    resumen: "resumen4",
    estado: "Pendiente",
    agente_califica: "",
    nombre: "Ana",
    apellido: "Ramírez",
    correo_electronico: "anaramirez@gmail.com",
    telefono: "+51 997 765 432",
    como_conociste_web: "Búsqueda en Internet",
    experiencia_inmobiliaria: "Avanzada",
    agente_externo: "Sí",
    departamento: "Lima",
    provincia: "Lima",
    distrito: "Miraflores",
    propiedades_asigandos: [],
    cuentanos:
      "Trabajo como corredora de bienes raíces en Miraflores, Lima. Mi experiencia avanzada me ha permitido manejar transacciones complejas y satisfacer las necesidades de mis clientes. Actualmente, tengo propiedades en venta y estoy comprometida a brindar un servicio de calidad. Siempre estoy abierta a nuevas oportunidades y desafíos en el dinámico mercado inmobiliario de Lima.",
  },
  {
    id: 5,
    resumen: "resumen5",
    estado: "Pendiente",
    agente_califica: "",
    nombre: "Jorge",
    apellido: "Pérez",
    correo_electronico: "jorgeperez@gmail.com",
    telefono: "+51 964 567 890",
    como_conociste_web: "Anuncio en TV",
    experiencia_inmobiliaria: "Intermedia",
    agente_externo: "No",
    departamento: "Lambayeque",
    provincia: "Chiclayo",
    distrito: "Chiclayo",
    propiedades_asigandos: [],
    cuentanos:
      "Me gustaría invertir en propiedades en Chiclayo, Lambayeque. Aunque mi experiencia inmobiliaria es intermedia, estoy en proceso de explorar oportunidades de inversión. Mi enfoque se ha centrado en la búsqueda de propiedades que ofrezcan un buen retorno de inversión. Estoy abierto a colaboraciones y a aprender más sobre el mercado inmobiliario de Chiclayo.",
  },
  {
    id: 6,
    resumen: "resumen6",
    estado: "Pendiente",
    agente_califica: "Bueno",
    nombre: "Carmen",
    apellido: "Torres",
    correo_electronico: "carmen.torres@gmail.com",
    telefono: "+51 955 123 456",
    como_conociste_web: "Evento Inmobiliario",
    experiencia_inmobiliaria: "Principiante",
    agente_externo: "Sí",
    departamento: "Tacna",
    provincia: "Tacna",
    distrito: "Tacna",
    propiedades_asigandos: [],
    cuentanos:
      "Quiero vender mi propiedad en Tacna. Aunque soy principiante en el ámbito inmobiliario, estoy entusiasmada por la posibilidad de vender mi propiedad de manera exitosa. He participado en eventos inmobiliarios para obtener más información sobre el proceso de venta. Estoy abierta a recibir asesoramiento y a explorar nuevas oportunidades en el mercado de bienes raíces de Tacna.",
  },
  {
    id: 7,
    resumen: "resumen7",
    estado: "Pendiente",
    agente_califica: "",
    nombre: "Luis",
    apellido: "Hernández",
    correo_electronico: "luishernandez@gmail.com",
    telefono: "+51 988 234 567",
    como_conociste_web: "Publicidad en periódico",
    experiencia_inmobiliaria: "Avanzada",
    agente_externo: "No",
    departamento: "Piura",
    provincia: "Piura",
    distrito: "Piura",
    propiedades_asigandos: [],
    cuentanos:
      "Tengo varias propiedades en venta en Piura. Con una experiencia avanzada en el mercado inmobiliario, estoy comprometido a ofrecer propiedades de calidad a mis clientes. Aunque mi estado actual es pendiente, estoy listo para completar transacciones exitosas y satisfacer las necesidades de aquellos que buscan comprar propiedades en Piura.",
  },
  {
    id: 8,
    resumen: "resumen8",
    estado: "Pendiente",
    agente_califica: "",
    nombre: "Mónica",
    apellido: "Gómez",
    correo_electronico: "monicagomez@gmail.com",
    telefono: "+51 977 345 678",
    como_conociste_web: "Referencia familiar",
    experiencia_inmobiliaria: "Intermedia",
    agente_externo: "Sí",
    departamento: "Ica",
    provincia: "Ica",
    distrito: "Ica",
    propiedades_asigandos: [],
    cuentanos:
      "Trabajo como asesora inmobiliaria en Ica. Mi experiencia intermedia me ha permitido asesorar a clientes en la compra y venta de propiedades en la ciudad de Ica. Mi conexión con clientes se basa en referencias familiares, lo que demuestra la confianza que mis clientes tienen en mis habilidades. Estoy abierta a nuevas oportunidades y desafíos en el mercado inmobiliario de Ica.",
  },
  {
    id: 9,
    resumen: "resumen9",
    estado: "Pendiente",
    agente_califica: "Excelente",
    nombre: "Rosa",
    apellido: "López",
    correo_electronico: "rosalopez@gmail.com",
    telefono: "+51 966 789 012",
    como_conociste_web: "Feria Inmobiliaria",
    experiencia_inmobiliaria: "Principiante",
    agente_externo: "No",
    departamento: "Junín",
    provincia: "Huancayo",
    distrito: "Huancayo",
    propiedades_asigandos: [],
    cuentanos:
      "Acabo de heredar una propiedad en Huancayo, Junín. Aunque soy principiante en el ámbito inmobiliario, estoy emocionada por explorar opciones para gestionar y posiblemente vender la propiedad heredada. Mi experiencia actual es completado con una calificación excelente, lo que indica una transacción exitosa. Estoy abierta a nuevas oportunidades en el mercado inmobiliario de Huancayo.",
  },
  {
    id: 10,
    resumen: "resumen10",
    estado: "Pendiente",
    agente_califica: "",
    nombre: "Pedro",
    apellido: "Martínez",
    correo_electronico: "pedromartinez@gmail.com",
    telefono: "+51 955 432 109",
    como_conociste_web: "Búsqueda en redes sociales",
    experiencia_inmobiliaria: "Avanzada",
    agente_externo: "Sí",
    departamento: "Loreto",
    provincia: "Iquitos",
    distrito: "Iquitos",
    propiedades_asigandos: [],
    cuentanos:
      "Invierto en propiedades en Iquitos, Loreto. Con una experiencia avanzada en el mercado inmobiliario de Iquitos, estoy listo para asumir nuevos desafíos y explorar oportunidades de inversión. Aunque mi estado actual es pendiente, estoy comprometido a continuar mi trayectoria exitosa en el mercado inmobiliario de Loreto.",
  },
  {
    id: 11,
    resumen: "resumen11",
    estado: "Aprobado",
    agente_califica: "Bueno",
    nombre: "Isabel",
    apellido: "Martínez",
    correo_electronico: "isabelmartinez@gmail.com",
    telefono: "+51 922 345 678",
    como_conociste_web: "Anuncio en revista",
    experiencia_inmobiliaria: "Intermedia",
    agente_externo: "No",
    departamento: "Arequipa",
    provincia: "Arequipa",
    distrito: "Cerro Colorado",
    cuentanos:
      "Con una experiencia intermedia, me especializo en propiedades en el distrito de Cerro Colorado, Arequipa. Ofrezco un servicio de calidad basado en la comprensión de las necesidades de mis clientes. Estoy dispuesta a explorar nuevas oportunidades y a brindar asesoramiento experto en el mercado inmobiliario local.",
    propiedades_asigandos: [
      {
        id: 2,
        codigo_de_propiedad: 2345678901234,
        estado: "Pendiente de realizar visita",
        ubicacion: "Avenida Arequipa, ciudad de Lima, Perú",
        direccion: "Avenida Arequipa 123",
        distrito: "Lince",
        provincia: "Lima",
        departamento: "Lima",
        codigo_postal: "15074",
        referencia: "Frente al parque",
        modalidad_de_propiedad: "Alquiler flex",
        categoria_de_propiedades: "Propiedad comercial",
        tipo_de_propiedad: "Oficina",
        propiedades: "2 propiedades",
        fecha: "Martes 15 de Diciembre",
        hora_de_inicio_visita: "10:00 am",
        hora_de_fin_visita: "11:30 am",
        primer_nombre: "Ana",
        primer_apellido: "Gómez",
        telefono: "+51 977 234 567",
        trabaja_con_agente: "Sí",
        detalle_adicional: "Buscando alquilar una propiedad a largo plazo.",
      },
    ],
  },
  {
    id: 12,
    resumen: "resumen12",
    estado: "Aprobado",
    agente_califica: "",
    nombre: "Juan",
    apellido: "López",
    correo_electronico: "juanlopez@gmail.com",
    telefono: "+51 933 987 654",
    como_conociste_web: "Publicidad en radio",
    experiencia_inmobiliaria: "Principiante",
    agente_externo: "Sí",
    departamento: "Cusco",
    provincia: "Cusco",
    distrito: "San Sebastián",
    propiedades_asigandos: [],
    cuentanos:
      "Soy un principiante en el mercado inmobiliario de San Sebastián, Cusco. Aunque estoy en proceso de aprender, estoy comprometido a ofrecer un servicio de calidad a mis clientes. Mi enfoque se centra en construir relaciones sólidas y comprender las necesidades específicas de aquellos que buscan propiedades en la zona.",
  },
  {
    id: 13,
    resumen: "resumen13",
    estado: "Aprobado",
    agente_califica: "Excelente",
    nombre: "Laura",
    apellido: "Rodríguez",
    correo_electronico: "laurarodriguez@gmail.com",
    telefono: "+51 944 567 890",
    como_conociste_web: "Búsqueda en redes sociales",
    experiencia_inmobiliaria: "Avanzada",
    agente_externo: "Sí",
    departamento: "Lima",
    provincia: "Lima",
    distrito: "Surco",
    propiedades_asigandos: [],
    cuentanos:
      "Con una experiencia avanzada en el mercado inmobiliario de Surco, Lima, me especializo en propiedades de lujo. Mi enfoque se centra en proporcionar un servicio personalizado y de alta calidad a clientes exigentes. Estoy abierta a colaboraciones y a continuar elevando los estándares en el mercado de bienes raíces.",
  },
  {
    id: 14,
    resumen: "resumen14",
    estado: "Aprobado",
    agente_califica: "",
    nombre: "Diego",
    apellido: "Herrera",
    correo_electronico: "diegoherrera@gmail.com",
    telefono: "+51 955 678 901",
    como_conociste_web: "Recomendación de colega",
    experiencia_inmobiliaria: "Intermedia",
    agente_externo: "No",
    departamento: "Piura",
    provincia: "Piura",
    distrito: "Castilla",
    propiedades_asigandos: [],
    cuentanos:
      "Trabajo como agente inmobiliario en Castilla, Piura. Mi experiencia intermedia me ha permitido entender las necesidades específicas del mercado local. Estoy comprometido a proporcionar un servicio confiable y a establecer relaciones sólidas con mis clientes. Estoy abierto a nuevas oportunidades y desafíos en el mercado inmobiliario de Piura.",
  },
  {
    id: 15,
    resumen: "resumen15",
    estado: "Aprobado",
    agente_califica: "Bueno",
    nombre: "Paola",
    apellido: "Sánchez",
    correo_electronico: "paolasanchez@gmail.com",
    telefono: "+51 933 456 789",
    como_conociste_web: "Evento de bienes raíces",
    experiencia_inmobiliaria: "Principiante",
    agente_externo: "Sí",
    departamento: "Tacna",
    provincia: "Tacna",
    distrito: "Alto de la Alianza",
    propiedades_asigandos: [],
    cuentanos:
      "Soy una principiante en el mercado inmobiliario de Alto de la Alianza, Tacna. Mi enfoque se centra en aprender y proporcionar un servicio de calidad a mis clientes. Estoy entusiasmada por explorar nuevas oportunidades y aprender más sobre el dinámico mercado inmobiliario de Tacna.",
  },
  {
    id: 16,
    resumen: "resumen16",
    estado: "Aprobado",
    agente_califica: "",
    nombre: "Roberto",
    apellido: "González",
    correo_electronico: "robertogonzalez@gmail.com",
    telefono: "+51 977 890 123",
    como_conociste_web: "Anuncio en línea",
    experiencia_inmobiliaria: "Avanzada",
    agente_externo: "No",
    departamento: "Lima",
    provincia: "Lima",
    distrito: "Barranco",
    propiedades_asigandos: [],
    cuentanos:
      "Con una experiencia avanzada en el mercado inmobiliario de Barranco, Lima, me especializo en propiedades con un toque artístico. Mi objetivo es ofrecer un servicio excepcional y encontrar las mejores opciones para mis clientes. Estoy listo para enfrentar nuevos desafíos y oportunidades en el mercado.",
  },
  {
    id: 17,
    resumen: "resumen17",
    estado: "Aprobado",
    agente_califica: "",
    nombre: "Cecilia",
    apellido: "Fuentes",
    correo_electronico: "ceciliafuentes@gmail.com",
    telefono: "+51 944 234 567",
    como_conociste_web: "Búsqueda en directorio",
    experiencia_inmobiliaria: "Intermedia",
    agente_externo: "Sí",
    departamento: "Arequipa",
    provincia: "Arequipa",
    distrito: "Cayma",
    propiedades_asigandos: [],
    cuentanos:
      "Como agente inmobiliaria en Cayma, Arequipa, tengo experiencia intermedia en el mercado local. Mi enfoque se centra en proporcionar soluciones a medida para mis clientes. Estoy abierta a nuevas oportunidades y a establecer relaciones sólidas en el dinámico mercado inmobiliario de Arequipa.",
  },
  {
    id: 18,
    resumen: "resumen18",
    estado: "Aprobado",
    agente_califica: "Excelente",
    nombre: "Gabriel",
    apellido: "Ortega",
    correo_electronico: "gabrielortega@gmail.com",
    telefono: "+51 955 567 890",
    como_conociste_web: "Redes Sociales",
    experiencia_inmobiliaria: "Principiante",
    agente_externo: "No",
    departamento: "Loreto",
    provincia: "Iquitos",
    distrito: "Belén",
    propiedades_asigandos: [],
    cuentanos:
      "Como principiante en el mercado inmobiliario de Belén, Iquitos, estoy emocionado por aprender y ofrecer un servicio de calidad. Mi enfoque se centra en comprender las necesidades de mis clientes y brindar soluciones efectivas. Estoy abierto a nuevas oportunidades y desafíos en el mercado de Loreto.",
  },
  {
    id: 19,
    resumen: "resumen19",
    estado: "Aprobado",
    agente_califica: "",
    nombre: "Valeria",
    apellido: "Rojas",
    correo_electronico: "valeriarojas@gmail.com",
    telefono: "+51 922 789 012",
    como_conociste_web: "Publicidad en televisión",
    experiencia_inmobiliaria: "Avanzada",
    agente_externo: "Sí",
    departamento: "Lima",
    provincia: "Lima",
    distrito: "Surquillo",
    propiedades_asigandos: [],
    cuentanos:
      "Con una experiencia avanzada en el mercado inmobiliario de Surquillo, Lima, me especializo en propiedades residenciales. Mi enfoque se centra en superar las expectativas de mis clientes y proporcionar asesoramiento experto. Estoy comprometida a seguir siendo líder en el dinámico mercado de bienes raíces.",
  },
  {
    id: 20,
    resumen: "resumen20",
    estado: "Aprobado",
    agente_califica: "Bueno",
    nombre: "Fernanda",
    apellido: "Herrera",
    correo_electronico: "fernandaherrera@gmail.com",
    telefono: "+51 933 123 456",
    como_conociste_web: "Recomendación de vecino",
    experiencia_inmobiliaria: "Intermedia",
    agente_externo: "No",
    departamento: "Cusco",
    provincia: "Cusco",
    distrito: "Wanchaq",
    propiedades_asigandos: [],
    cuentanos:
      "Como agente inmobiliaria en Wanchaq, Cusco, tengo experiencia intermedia en el mercado local. Me enorgullece ofrecer un servicio de calidad y construir relaciones sólidas con la comunidad. Estoy abierta a nuevas oportunidades y a continuar sirviendo a mis clientes con profesionalismo.",
  },
  {
    id: 21,
    resumen: "resumen2",
    estado: "Aprobado",
    agente_califica: "",
    nombre: "Carolina",
    apellido: "Gutiérrez",
    correo_electronico: "carolinagutierrez@gmail.com",
    telefono: "+51 977 654 321",
    como_conociste_web: "Búsqueda en directorio",
    experiencia_inmobiliaria: "Intermedia",
    agente_externo: "Sí",
    departamento: "Lima",
    provincia: "Lima",
    distrito: "San Isidro",
    propiedades_asigandos: [],
    cuentanos:
      "Con experiencia intermedia en el sector inmobiliario, me especializo en propiedades de lujo en San Isidro, Lima. Mi objetivo es proporcionar asesoramiento personalizado y encontrar propiedades que se adapten a los gustos y necesidades de mis clientes. Estoy abierta a nuevas oportunidades y desafíos en este exclusivo mercado.",
  },
  {
    id: 22,
    resumen: "resumen3",
    estado: "Aprobado",
    agente_califica: "Bueno",
    nombre: "Martín",
    apellido: "Herrera",
    correo_electronico: "martinherrera@gmail.com",
    telefono: "+51 955 789 012",
    como_conociste_web: "Anuncio en revista",
    experiencia_inmobiliaria: "Avanzada",
    agente_externo: "No",
    departamento: "Lima",
    provincia: "Lima",
    distrito: "San Isidro",
    propiedades_asigandos: [],
    cuentanos:
      "Con más de 10 años de experiencia en el mercado inmobiliario de San Isidro, me especializo en propiedades residenciales y comerciales. Mi enfoque se basa en la integridad, la atención personalizada y la satisfacción del cliente. Estoy listo para asumir nuevos desafíos y continuar superando las expectativas en este exclusivo distrito.",
  },
  {
    id: 23,
    resumen: "resumen4",
    estado: "Aprobado",
    agente_califica: "",
    nombre: "Laura",
    apellido: "Vargas",
    correo_electronico: "lauravargas@gmail.com",
    telefono: "+51 922 456 789",
    como_conociste_web: "Recomendación de colega",
    experiencia_inmobiliaria: "Principiante",
    agente_externo: "Sí",
    departamento: "Lima",
    provincia: "Lima",
    distrito: "San Isidro",
    propiedades_asigandos: [],
    cuentanos:
      "Soy una agente principiante en San Isidro, Lima. Aunque estoy en proceso de aprendizaje, mi objetivo es ofrecer un servicio de calidad a mis clientes. Mi enfoque se centra en la atención personalizada y en construir relaciones sólidas. Estoy abierta a nuevas oportunidades y a crecer en este exclusivo mercado.",
  },
];

export const dataClientes = [
  {
    id: 1,
    estado: "Pendiente",
    modalidad: "Alquiler tradicional",
    fecha: "Domingo 26 de Noviembre",
    hora_de_inicio: "2:00 pm",
    hora_de_fin: "4:00 pm",
    primer_nombre: "Jesús",
    primer_apellido: "Alzamora",
    telefono: "+51 983 159 445",
    trabaja_con_agente: "No",
    detalle_adicional:
      "Quisiera que el agente me llame cuando esté por llegar a la propiedad.",
  },
  {
    id: 2,
    estado: "Pendiente",
    modalidad: "Compra",
    fecha: "Sábado 10 de Diciembre",
    hora_de_inicio: "11:00 am",
    hora_de_fin: "1:00 pm",
    primer_nombre: "María",
    primer_apellido: "López",
    telefono: "+51 977 123 456",
    trabaja_con_agente: "Sí",
    detalle_adicional: "Busco una propiedad con al menos 3 habitaciones.",
  },
  {
    id: 3,
    estado: "Pendiente",
    modalidad: "Alquiler flex",
    fecha: "Viernes 5 de Febrero",
    hora_de_inicio: "3:30 pm",
    hora_de_fin: "5:30 pm",
    primer_nombre: "Carlos",
    primer_apellido: "Ramírez",
    telefono: "+51 955 789 123",
    trabaja_con_agente: "No",
    detalle_adicional: "Preferiría propiedades con terraza.",
  },
  {
    id: 4,
    estado: "Pendiente",
    modalidad: "Alquiler tradicional",
    fecha: "Martes 20 de Marzo",
    hora_de_inicio: "1:00 pm",
    hora_de_fin: "3:00 pm",
    primer_nombre: "Laura",
    primer_apellido: "Martínez",
    telefono: "+51 964 321 876",
    trabaja_con_agente: "Sí",
    detalle_adicional:
      "Interesada en propiedades con buena iluminación natural.",
  },
  {
    id: 5,
    estado: "Pendiente",
    modalidad: "Alquiler flex",
    fecha: "Domingo 10 de Abril",
    hora_de_inicio: "4:00 pm",
    hora_de_fin: "6:00 pm",
    primer_nombre: "Alejandro",
    primer_apellido: "Díaz",
    telefono: "+51 910 876 543",
    trabaja_con_agente: "No",
    detalle_adicional: "Requiere acceso a zonas deportivas cercanas.",
  },
];

export const dataCargarArchivos = [
  {
    title: "Contrato de intermediación:",
    button: "Seleccionar archivo",
  },
  {
    title: "Dni propietarios:",
    button: "Seleccionar archivo",
  },
  {
    title: "HR(Hoja resumen):",
    button: "Seleccionar archivo",
  },
  {
    title: "PU(Predio urbano):",
    button: "Seleccionar archivo",
  },
  {
    title: "Partida electrónica:",
    button: "Seleccionar archivo",
  },
];
